from flask import Flask, render_template
import yt_dlp as ytdlp

app = Flask(__name__)

# Helper function - for downloading videos from YouTube URL
def download_vid_as_mp3(url):
	ytdlp_options = {
	    'outtmpl' : 'songs/%(title)s.%(ext)s',
	    'postprocessors' : [{
	        'key' : 'FFmpegExtractAudio',
	        'preferredcodec' : 'mp3',
        }],
    }
	with ytdlp.YoutubeDL(ytdlp_options) as ydl:
		ydl.download(url)

# Helper Function - for searching YouTube.
# Instead of the user looking at YouTube directly,
# it will be the server tapping into YouTube.
def search_vid(search_query):
    ytdlp_options = {
        'default_search' : 'ytsearch10',
    }
    with ytdlp.YoutubeDL(ytdlp_options) as ydl:
        results = ydl.extract_info(search_query, download=False)['entries']
        songs = []
        for video_info in results:
            song = {
                'name' : video_info['title'],
                'id' : video_info['id']
            }
            songs.append(song)
    return songs

@app.route('/tests/downloader')
def downloader_tests():
	# Link generated by YouTube app on Android
	url_song = 'https://youtu.be/wvZXe0wFttU'
	download_vid_as_mp3(url_song)
	return 'Download Tester. See terminal.'

@app.route('/tests/searcher')
def searcher_tests():
	search_query_test = 'Moranbong Band'
	results_unfiltered = search_vid(search_query_test)
	print(results_unfiltered)
	return render_template('searchtest.html', title="Search Tester", results=results_unfiltered)

@app.route('/')
def hello():
	return render_template('main.html', title="Hoie")
    #return 'Hello, World!'
    
@app.route('/admin')
def admin():
	return 'Admin Page Here for downloading songs'
	