from flask import Flask, render_template
import yt_dlp as ytdlp

app = Flask(__name__)

def download_vid_as_mp3(url):
	ytdlp_options = {
	    'postprocessors' : [{
	        'key' : 'FFmpegExtractAudio',
	        'preferredcodec' : 'mp3',
        }],
    }
	with ytdlp.YoutubeDL(ytdlp_options) as ydl:
		ydl.download(url)

@app.route('/tests/downloader')
def downloader_tests():
	# Link generated by YouTube app on Android
	url_song = 'https://youtu.be/wvZXe0wFttU'
	download_vid_as_mp3(url_song)
	return 'Download Tester. See terminal.'

@app.route('/')
def hello():
	return render_template('main.html', title="Hoie")
    #return 'Hello, World!'
    
@app.route('/admin')
def admin():
	return 'Admin Page Here for downloading songs'
	